config/routes.rb
PollingTest::Application.routes.draw do
  
  resources :sensors do
    collection do
      get :index
      get :start
      get :stop
      get :get_data
      post :post_data
      get :test_json
      post :delete_all
      get :stream
    end
  end
  
  root :to => "sensors#index"

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
    
  def index
    start
    get_data
  end

  def start
    unless Thread.main[:listener].class == Listener
      Thread.main[:listener] = Listener.new 
    end
    listener = Thread.main[:listener]
    if listener.read != 1
      listener.read = 1
      listener.listen
    end
  end
  
  def stop
    listener = Thread.main[:listener]
    listener.read = 0
  end
  
  def get_data   
    @listener = Thread.main[:listener]
    @limit = 100
    if @listener.hr_buffer.array.present?
      @hr_data = @listener.hr_buffer.array
      @bpm = @listener.hr_buffer.bpm
    end
    if @listener.sw_buffer.array.present?
      @sw_data = @listener.sw_buffer.array
    end
    if @listener.mt_buffer.array.present?
      @mt_data = @listener.mt_buffer.array
    end
    if @listener.accel_buffer.array.present?
      @accel_data = @listener.accel_buffer.array
    end
    if @listener.gyro_buffer.array.present?
      @gyro_data = @listener.gyro_buffer.array
    end
    if @listener.geo_buffer.array.present?
      @latitude, @longitude = @listener.geo_buffer.array.last
    end
    if @listener.peac_buffer.array.present?
      @peak_accel_data = @listener.peac_buffer.array
    end
    if @listener.post_buffer.array.present?
      @posture_data = @listener.post_buffer.array
    end
    if @listener.resp_buffer.array.present?
      @respiration_data = @listener.resp_buffer.array
    end
    if @listener.eeg_buffer.array.present?
      @eeg_data = @listener.eeg_buffer.array
    end
  end
  
  def post_data
    Rails.logger.warn("========== PARAMETERS: " + params.inspect)
    not_saved = false
    if params["latitude"] && params["longitude"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => GEOLOCATION, 
                                    :value1 => params["latitude"].to_f, 
                                    :value2 => params["longitude"].to_f)
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["GSR"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => SWEAT, 
                                    :value1 => params["GSR"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["EMG"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => MUSCLETENSION, 
                                    :value1 => params["EMG"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["AccelerometerX"] && params["AccelerometerY"] && params["AccelerometerZ"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => ACCELEROMETER, 
                                    :value1 => params["AccelerometerX"], 
                                    :value2 => params["AccelerometerY"], 
                                    :value3 => params["AccelerometerZ"])      
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["GyroscopeX"] && 
      params["GyroscopeY"] && params["GyroscopeZ"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => GYROSCOPE, 
                                    :value1 => params["GyroscopeX"], 
                                    :value2 => params["GyroscopeY"], 
                                    :value3 => params["GyroscopeZ"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["HEARTBIT"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => HEARTRATE, 
                                    :value1 => params["HEARTBIT"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["RESPIRATION"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => RESPIRATION, 
                                    :value1 => params["RESPIRATION"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["PEAKACCE"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => PEAKACCEL, 
                                    :value1 => params["PEAKACCE"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if params["POSTURE"]
      measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                    :measurement_time => Time.at(params["time"].to_f / 1000), 
                                    :sensor_type => POSTURE, 
                                    :value1 => params["POSTURE"])
      if measure.valid? && RawMeasurement.count < 10000
        measure.save 
      else
        not_saved = true
      end
    end
    if (params["ATTENTION"] && 
        params["MEDITATION"] && 
        params["DELTA"] && 
        params["THETA"] && 
        params["LOWALPHA"] && 
        params["HIGHALPHA"] && 
        params["LOWBETA"] && 
        params["HIGHBETA"] && 
        params["LOWGAMMA"] && 
        params["MIDGAMMA"])
        measure = RawMeasurement.new(:source_id => params["id_sensor"], 
                                      :measurement_time => Time.at(params["time"].to_f / 1000), 
                                      :sensor_type => EEG, 
                                      :value1 => params["ATTENTION"].to_f, 
                                      :value2 => params["MEDITATION"].to_f,
                                      :value3 => params["DELTA"].to_f,
                                      :value4 => params["THETA"].to_f,
                                      :value5 => params["LOWALPHA"].to_f,
                                      :value6 => params["HIGHALPHA"].to_f,
                                      :value7 => params["LOWBETA"].to_f,
                                      :value8 => params["HIGHBETA"].to_f,
                                      :value9 => params["LOWGAMMA"].to_f,
                                      :value10 => params["MIDGAMMA"].to_f)
        if measure.valid? && RawMeasurement.count < 10000
          measure.save 
        else
          not_saved = true
        end
      end
      begin 
      if not_saved 
        render :json => {"saved" => false, "id" => measure.source_id}
      else
        render :json => {"saved" => true, "id" => measure.source_id};
      end
    rescue Exception => e
      render :json => {"error" => "#{e.message}"}
    end
  end
  
  def test_json
    render :json => {"status" => "ok"}
  end
  
  def delete_all
    Textlogger.delete_all
    RawMeasurement.delete_all
    redirect_to :action => :index
  end
  
end

app/views/sensors/_accelerometer.html.erb
Accelerometer raw data:<br/>
<%#= @accel_data.inspect %>
<div id="accelerometer_plot"></div>

app/views/sensors/_eeg.html.erb
Eeg  data:<br/>
<div id="eeg_plot"></div>

app/views/sensors/_eeg_current.html.erb
Eeg raw data:<br/>
<div id="eeg_current_plot"></div>

app/views/sensors/_gyroscope.html.erb
Gyroscope raw data: <br/>
<%#= @gyro_data.inspect %>
<div id="gyroscope_plot"></div>

app/views/sensors/_heart_rate.html.erb
<!-- <div id="live_heart_rate_plot"></div> -->
<div id="bpm_rate_plot" style=""></div>
<div id="bpm_value" style="">
	<div class="header">
		<strong>Current heartbeat</strong>
	</div>
	<div class="bpm-value">
	</div>
</div>
<div class="clearfix"></div>

app/views/sensors/_map.html.erb
<img src="http://maps.googleapis.com/maps/api/staticmap?maptype=hybrid&zoom=16&size=250x250&format=png32&markers=color:blue%7Clabel:Location%7C<%= @latitude %>,<%= @longitude %>&sensor=true"/>

app/views/sensors/_muscle_tension.html.erb
Muscle tension raw data: <br/>
<%#= @mt_data.inspect %>
<div id="muscle_tension_plot"></div>

app/views/sensors/_peak_accel.html.erb
Peak acceleration raw data: <br/>
<%#= @mt_data.inspect %>
<div id="peak_accel_plot"></div>

app/views/sensors/_posture.html.erb
Posture raw data: <br/>
<%#= @mt_data.inspect %>
<div id="posture_plot"></div>

app/views/sensors/_sweat.html.erb
Sweat level raw data: <br/>
<%#= @sw_data.inspect %>
<div id="sweat_plot"></div>

app/views/sensors/get_data.js.erb
/* clear arrays */

heart_rate_data = [];
sweat_data = [];
muscle_data = [];
accelero_data_x = [];
accelero_data_y = [];
accelero_data_z = [];
gyro_data_x = [];
gyro_data_y = [];
gyro_data_z = [];
peac_data = [];
post_data = [];
resp_data = [];
eeg_data1 = [];
eeg_data2 = [];
eeg_current = [];

/* Heart rate */
<% if @hr_data.present? %>
	<% i = 0 %>
	<% @hr_data.each do |data_entry| %>
		heart_rate_data.push([<%= i %>, <%= data_entry %> ]);
		<% i += 1 %>
	<% end %>
	if (heart_rate_data.size >= <%= @limit %>){
		heart_rate_data.shift()
	}
<% end %>

/* Draw average BPM */
<% if @bpm.present? %>
	current_bpm = <%= @bpm %>;
	current_bpm = current_bpm.toFixed(1);
	$(".bpm-value").html(current_bpm);
<% end %>

/* Sweat */
<% if @sw_data.present? %>
	<% i = 0 %>
	<% @sw_data.each do |data_entry| %>
		sweat_data.push([<%= i %>, <%= data_entry%>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Muscle tension */
<% if @mt_data.present? %>
	<% i = 0 %>
	<% @mt_data.each do |data_entry| %>
		muscle_data.push([<%= i %>, <%= data_entry%>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Accelerometer */
<% if @accel_data.present? %>
	<% i = 0 %>
	<% @accel_data.each do |data_entry| %>
		accelero_data_x.push([<%= i %>, <%= data_entry[0] %>]);
		accelero_data_y.push([<%= i %>, <%= data_entry[1] %>]);
		accelero_data_z.push([<%= i %>, <%= data_entry[2] %>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Gyroscope */
<% if @gyro_data.present? %>
	<% i = 0 %>
	<% @gyro_data.each do |data_entry| %>
		gyro_data_x.push([<%= i %>, <%= data_entry[0] %>]);
		gyro_data_y.push([<%= i %>, <%= data_entry[1] %>]);
		gyro_data_z.push([<%= i %>, <%= data_entry[2] %>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Peak acceleration */
<% if @peak_accel_data.present? %>
	<% i = 0 %>
	<% @peak_accel_data.each do |data_entry| %>
		peac_data.push([<%= i %>, <%= data_entry%>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Posture */
<% if @posture_data.present? %>
	<% i = 0 %>
	<% @posture_data.each do |data_entry| %>
		post_data.push([<%= i %>, <%= data_entry%>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Respiration */
<% if @respiration_data.present? %>
	<% i = 0 %>
	<% @respiration_data.each do |data_entry| %>
		resp_data.push([<%= i %>, <%= data_entry%>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Eeg */
<% if @eeg_data.present? %>
	<% i = 0 %>
	<% last = @eeg_data.last %>
	eeg_current = [
	    {color:"rgb(13,132,196)", data: [[1, <%= last[2] %>]]},
	    {color:"rgb(14,140,98)", data: [[2, <%= last[3] %>]]},
	    {color:"rgb(24,148,37)", data: [[3, <%= last[4] %>]]},
	    {color:"rgb(105,176,17)", data: [[4, <%= last[5] %>]]},
	    {color:"rgb(176,197,15)", data: [[5, <%= last[6] %>]]},
	    {color:"rgb(252,207,3)", data: [[6, <%= last[7] %>]]},
	    {color:"rgb(221,104,11)", data: [[7, <%= last[8] %>]]},
	    {color:"rgb(201,31,22)", data: [[8, <%= last[9] %>]]}
	];
	<% @eeg_data.each do |data_entry| %>
		eeg_data1.push([<%= i %>, <%= data_entry[0]%>]);
		eeg_data2.push([<%= i %>, <%= data_entry[1]%>]);
		<% i += 1 %>
	<% end %>
<% end %>

/* Geolocation */
<% if @latitude.present? && @longitude.present? %>
	$("#geolocation").html("<%= j(render :partial => 'map') %>")
<% end %>

app/views/sensors/index.html.erb
<div id="wrapper">
	<h1>Me Machine live readings</h1>
	<div class="container">
		<div id="heart_rate">
			<%= render :partial => "heart_rate" %>
		</div>
	</div>
	<div class="container">
		<div id="geolocation">
			<%= render :partial => "map" %>
		</div>
	</div><br/>
	<div class="container">
		<div id="sweat">
			<%= render :partial => "sweat" %>
		</div>
	</div>
	<div class="container">
		<div id="muscle_tension">
			<%= render :partial => "muscle_tension" %>
		</div>
	</div><br/>
	<div class="container">
		<div id="accelerometer">
			<%= render :partial => "accelerometer" %>
		</div>
	</div>
	<div class="container">
		<div id="gyroscope">
			<%= render :partial => "gyroscope" %>
		</div>
	</div>
	<div class="container">
		<div id="peak_accel">
			<%= render :partial => "peak_accel" %>
		</div>
	</div>
	<div class="container">
		<div id="posture">
			<%= render :partial => "posture" %>
		</div>
	</div>
	<div class="container">
		<div id="respiration">
			<%= render :partial => "respiration" %>
		</div>
	</div>
	<div class="container">
		<div id="eeg">
			<%= render :partial => "eeg" %>
		</div>
	</div>
	<div class="container">
		<div id="eeg_current">
			<%= render :partial => "eeg_current" %>
		</div>
	</div>
	<div class="clearfix"></div>
	<p>
		<a id="start" href="#">Start</a>
		<a id="stop" href="#">Stop</a>
	</p>
</div>
<p>
<!-- POSTS log:<br/>
<%# @logger.each do |log_entry| %>
	<%#= log_entry.created_at %> || <%#= log_entry.content %> <br/>
<%# end %><br/>-->
<a id="test_post" href="#">Test post action</a> <%#= @post_count %><br/>
<%= link_to "Clear database", delete_all_sensors_path, :method => :post %>
</p>

<div id="debug" style="display:none;">
	### Debug information ### </br>
	listener: <%= @listener.inspect %><br/>
	buffer.get_data: <%= @listener.geo_buffer.get_data %><br/>
	buffer.get_data.last: <%= @listener.geo_buffer.get_data.last %><br/>
	Latitude: <%= @latitude %><br/>
	Longitude: <%= @longitude %><br/>
	<br/>
	Rows in database: <%= RawMeasurement.count %> (limit 10.000)
	<%= Thread.main[:listener]%><br/>
	===<br/>
	<%= Thread.main[:hr_buffer]%><br/>
	<%= Thread.main[:sw_buffer]%><br/>
	<%= Thread.main[:mt_buffer]%><br/>
  <%= Thread.main[:accel_buffer]%><br/>
  <%= Thread.main[:gyro_buffer]%><br/>
  <%= Thread.main[:geo_buffer]%><br/>
  <%= Thread.main[:resp_buffer]%><br/>
  <%= Thread.main[:peac_buffer]%><br/>
  <%= Thread.main[:post_buffer]%><br/>
  <%= Thread.main[:eeg_buffer]%><br/>
</div>

<script type="text/javascript">
	$(document).ready(function($){
		debug = "";
		$("#test_post").click(function(e){
			$.ajax({
				url: "<%= url_for(:action => :post_data) %>",
				type: 'POST',
				dataType: 'json',
				data: {
					AccelerometerX: "1911.1234",
					AccelerometerY: "1227.7454",
					AccelerometerZ: "1532.2353"
				},
			  success: function(data){
				debug = data
			    alert('success! \nstatus: ' + data);
			  },
			  error: function(data){
			    alert('failure: ' + data);
			  }
			});
		});
	})
</script>

app/views/sensors/start.html.erb
Sensor reading started.

app/views/sensors/stop.html.erb
Sensor reading stopped.